foundriesio/lmp-tools

scripts/update-factory-manifest

This is a series of fixes to migrate and update the update-factory-manifest script:
- import current version of the script from lmp-manifest
- make git command which looks up the current branch compatible with older git versions
- bugfix to finding the latest tag upstream
- dont assume master branch just exit with warning message

Update script fixes

---

scripts/update-factory-manifest

Use describe on fetch head (available after git fetch) as a way to find
the latest tag that is available on lmp-manifest upstream. Calling
describe without pointing out a reference makes it use what is head from
the running branch (one to be updated to).
Signed-off-by: Ricardo Salveti <ricardo@foundries.io>

update-factory-manifest: use describe on fetch head

---

security/imx_hab4/sign-file.sh

Also changes so it can use what is in the directory
or the naming that the NXP utilities generate.

Add an option to set the key index to use for signing

---

security/imx_hab4/sign-file.sh

The updated cst tools validates the Unlock block in the config
file. That means that the Unlock section should be removed for
an Engine of SW.

security: imx_hab4: sign-file.sh update for CST 3.3.1

---

security/imx_hab4/sign-file.sh

Currently, we allow badly formed parameters in the sign-file script.
This is definitely not desirable.  Let's instead generate an error
message and return an error code.
Example of badly formed parameter:
$ ./sign-file.sh --cst ./cst --enigne SW --spl SPL-test
Unknown param: '--enigne'!
Signed-off-by: Michael Scott <mike@foundries.io>

imx_hab4: sign-file: error on bad params

---

security/imx_hab4/sign-file.sh

The CST program prints out an intermediate file that can be
miss leading so remove the repot of the file from the CST and
add the name of the file this script creates.

Security: sign-file.sh: report the result file

---

security/imx6/gen_close.sh
security/imx6ul/gen_close.bat
security/imx6ul/gen_close.sh
security/imx7ulpea-ucom/gen_close.sh
security/imx8m/gen_close.sh

If the board fails to close the script was completing with no
failures. This will cause a timeout error making uuu exit with
an failure count and an error return to the shell.

security: update gen_close scripts to error if close fails

---

scripts/list-updates-in-meta-lmp

This script will list all "Relevant changes" in the meta-lmp
repository since the last lmp-manifest update.
It requires the meta-lmp repository checked out and current.
This assumes you are in the top directory of lmp-manifest repo
and the meta-lmp repo is checked out as ../meta-lmp.
It does however have options to specify where the meta-lmp repo
is checked out.
Also, it does not look in the checked out lmp-manifest but grabs
the last meta-lmp revision from github.com/foundriesio/lmp-manifest
directly.

scripts: Add a script to list changes since last lmp-manifest update

---

security/imx8m/gen_close.sh
security/imx8m/gen_fuse.sh

imx8m uses imx-boot as SPL so change the name accordingly for the
gen scripts.
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

security: imx8m: change SPL to imx-boot for gen scripts

---

security/imx8m/gen_close.sh
security/imx8m/gen_fuse.sh

Using SDPU command makes the imx8mmevk board hang, so fix it to use SDPV commands.
Also emmc device for this board is at mmc dev 2, so use this as default on gen_close.uuu.

security: imx8m: general fixes

---

security/imx7ulpea-ucom/gen_close.sh
security/imx7ulpea-ucom/gen_fuse.sh

The jump SDPU commands made the board hang, so fix it using the SDPV commands.
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

security: imx7ulp: fix SDP commands

---

security/imx_hab4/sign-file.sh

It fixes the use of another key other than first one
Signed-off-by: Daiane Angolini <daiane.angolini@foundries.io>

security: imx_hab4: sign-file: Fix typo

---

security/imx_ahab/sign-file.sh

Don't remove ${WORK_FILE}_csf.bin file in the end of script, as in the
current version it's not created.
Signed-off-by: Igor Opaniuk <igor.opaniuk@foundries.io>

security: imx_ahab: drop removing non-existing file

---

security/imx8mp/gen_close.sh
security/imx8mp/gen_fuse.sh

iMX8MP uses SDPS instead of SDP protocol for the boot command, so fix this.
Signed-off-by: Vanessa Maegima <vanessa.maegima@foundries.io>

security: imx_hab4: add imx8mp gen_fuse and gen_close scripts

---

scripts/update-factory-manifest

This can update a partners factory lmp-manifest if the parent manifest
is public.
For a derivative factory the '**conf/update-manifest.conf**' if present will point to the upstream lmp-manifest and the tag prefix.
Invoke the command while sitting in the lmp-manifest checked out directory of the derivative factory:
`<path to tool>/update-factory-manifest`
For the parent factory, the repo should contain a release branch with prefixed tags like **partner-86** and that branch should contain the conf file or it can be created by:
`<path to tool>/update-factory-manifest --url https://github.com/<partner>/lmp-manifest.git --prefix partner --write-conf`
while sitting in the lmp-manifest release branch.

scripts: update-factory-manifest: add partner factory update support

---

scripts/update-factory-manifest

The "git describe" appears to only work on the default
branch and not tags from all branches so it is necessary
to change the method of finding the latest upstream
tag to use for a partner factory lmp-manifest update.

scripts: Update the method of finding the upstream tag

---

security/imx8qm/gen_close.sh
security/imx8qm/gen_fuse.sh

The generation scripts were missing for fuse and close on the imx8qm. This adds them

security: add gen_fuse/close scripts for imx8qm

---

scripts/rotate_ci_keys.sh

This script is used to rotate CI keys which means these are not insecure development keys.  Let's not call them that as they are logged in dmesg on boot.

rotate_ci_keys: adjust kernel module signing key name

---

scripts/update-factory-manifest

This avoids pulling a bunch of "extra" tags when looking for partner manifest tag updates.  These tags end up cluttering derivative Factories.
No change when PREFIX is not set.

update-factory-manifest: if present only pull and push tags that match PREFIX

---

scripts/update-factory-manifest

Drop complicated git ls-remote and use quotes around tag filter

fixup: update-factory-manifest: bugfix for matching PREFIX when pulling tags

---

security/imx8qm/gen_close.sh
security/imx8qm/gen_fuse.sh

This reverts commit e2eba455a825a8da4761755086fb38a5ae577870.
As discussed with the platform team, a "reboot" is required for a full PoR of the board, so revert this.

Revert "security: imx8qm: replace "reboot" command"

---

security/uefi/gen_uefi_certs.sh

Using invalid variable names (ie, capital) will cause errors during key
rotation. This is because during user mode the PKCS7 authenticator will
verify the payload before updating the key.
Those errors do not occur during provisioning because in SetupMode there
is no authentication done for db/dbx (only PK).
Signed-off-by: Jorge Ramirez-Ortiz <jorge@foundries.io>

uefi: fix gen_uefi_certs.sh

---

security/uefi/README.txt
security/uefi/gen_uefi_certs.sh

In order to un-provision a board, removing the certificates in operation is required.
We will follow the UEFI specification for that.

uefi: support un-provisioning tool

---

scripts/update-factory-manifest

The script does not operate with point releases.
This updates to include point releases.

fixup: script update-factory-manifest
